package config



































































































































}	return defaultValue	}		}			return duration		if duration, err := time.ParseDuration(value); err == nil {	if value := os.Getenv(key); value != "" {func getEnvAsDuration(key string, defaultValue time.Duration) time.Duration {}	return defaultValue	}		}			return intValue		if intValue, err := strconv.Atoi(value); err == nil {	if value := os.Getenv(key); value != "" {func getEnvAsInt(key string, defaultValue int) int {}	return defaultValue	}		return value	if value := os.Getenv(key); value != "" {func getEnv(key, defaultValue string) string {}	return cfg, nil	}		return nil, fmt.Errorf("PASETO_SECRET_KEY must be at least 32 bytes")	if len(cfg.PasetoSecretKey) < 32 {	}		return nil, fmt.Errorf("PASETO_SECRET_KEY is required")	if cfg.PasetoSecretKey == "" {	// Validate required fields	}		RateLimitDuration: getEnvAsDuration("RATE_LIMIT_DURATION", time.Minute),		RateLimitMax:      getEnvAsInt("RATE_LIMIT_MAX", 100),		// Rate Limiting		CORSOrigins: getEnv("CORS_ORIGINS", "http://localhost:3000"),		// CORS		OAuthGitHubRedirectURL:  getEnv("OAUTH_GITHUB_REDIRECT_URL", ""),		OAuthGitHubClientSecret: getEnv("OAUTH_GITHUB_CLIENT_SECRET", ""),		OAuthGitHubClientID:     getEnv("OAUTH_GITHUB_CLIENT_ID", ""),		OAuthGoogleRedirectURL:  getEnv("OAUTH_GOOGLE_REDIRECT_URL", ""),		OAuthGoogleClientSecret: getEnv("OAUTH_GOOGLE_CLIENT_SECRET", ""),		OAuthGoogleClientID:     getEnv("OAUTH_GOOGLE_CLIENT_ID", ""),		// OAuth		RefreshTokenDuration: getEnvAsDuration("REFRESH_TOKEN_DURATION", 168*time.Hour),		SessionDuration:      getEnvAsDuration("SESSION_DURATION", 24*time.Hour),		PasetoSecretKey:      getEnv("PASETO_SECRET_KEY", ""),		// Authentication		RedisDB:       getEnvAsInt("REDIS_DB", 0),		RedisPassword: getEnv("REDIS_PASSWORD", ""),		RedisURL:      getEnv("REDIS_URL", "redis://localhost:6379"),		// Redis		DBMinConns:  getEnvAsInt("DB_MIN_CONNECTIONS", 10),		DBMaxConns:  getEnvAsInt("DB_MAX_CONNECTIONS", 100),		DBSchema:    getEnv("DB_SCHEMA", "authenserver_service"),		DBName:      getEnv("DB_NAME", "skoservice"),		DBPassword:  getEnv("DB_PASSWORD", "postgres"),		DBUser:      getEnv("DB_USER", "postgres"),		DBPort:      getEnvAsInt("DB_PORT", 5432),		DBHost:      getEnv("DB_HOST", "localhost"),		DatabaseURL: getEnv("DATABASE_URL", ""),		// Database		Environment: getEnv("ENVIRONMENT", "development"),		Port:        getEnv("PORT", "8080"),	cfg := &Config{func Load() (*Config, error) {}	RateLimitDuration time.Duration	RateLimitMax      int	// Rate Limiting	CORSOrigins string	// CORS	OAuthGitHubRedirectURL  string	OAuthGitHubClientSecret string	OAuthGitHubClientID     string		OAuthGoogleRedirectURL  string	OAuthGoogleClientSecret string	OAuthGoogleClientID     string	// OAuth	RefreshTokenDuration  time.Duration	SessionDuration       time.Duration	PasetoSecretKey       string	// Authentication	RedisDB       int	RedisPassword string	RedisURL      string	// Redis	DBMinConns      int	DBMaxConns      int	DBSchema        string	DBName          string	DBPassword      string	DBUser          string	DBPort          int	DBHost          string	DatabaseURL     string	// Database	Environment string	Port        string	// Servertype Config struct {)	"time"	"strconv"	"os"	"fmt"import (package config