// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO authenserver_service.accounts (
    id, user_id, type, provider, provider_account_id,
    refresh_token, access_token, expires_at, token_type,
    scope, id_token, session_state
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, user_id, type, provider, provider_account_id, refresh_token, access_token, expires_at, token_type, scope, id_token, session_state
`

type CreateAccountParams struct {
	Column1  pgtype.Text `json:"column_1"`
	Column2  pgtype.Text `json:"column_2"`
	Column3  pgtype.Text `json:"column_3"`
	Column4  pgtype.Text `json:"column_4"`
	Column5  pgtype.Text `json:"column_5"`
	Column6  pgtype.Text `json:"column_6"`
	Column7  pgtype.Text `json:"column_7"`
	Column8  pgtype.Int8 `json:"column_8"`
	Column9  pgtype.Text `json:"column_9"`
	Column10 pgtype.Text `json:"column_10"`
	Column11 pgtype.Text `json:"column_11"`
	Column12 pgtype.Text `json:"column_12"`
}

type CreateAccountRow struct {
	ID                string      `json:"id"`
	UserID            string      `json:"user_id"`
	Type              string      `json:"type"`
	Provider          string      `json:"provider"`
	ProviderAccountID string      `json:"provider_account_id"`
	RefreshToken      pgtype.Text `json:"refresh_token"`
	AccessToken       pgtype.Text `json:"access_token"`
	ExpiresAt         pgtype.Int8 `json:"expires_at"`
	TokenType         pgtype.Text `json:"token_type"`
	Scope             pgtype.Text `json:"scope"`
	IDToken           pgtype.Text `json:"id_token"`
	SessionState      pgtype.Text `json:"session_state"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Column10,
		arg.Column11,
		arg.Column12,
	)
	var i CreateAccountRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Provider,
		&i.ProviderAccountID,
		&i.RefreshToken,
		&i.AccessToken,
		&i.ExpiresAt,
		&i.TokenType,
		&i.Scope,
		&i.IDToken,
		&i.SessionState,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM authenserver_service.accounts
WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, dollar_1 pgtype.Text) error {
	_, err := q.db.Exec(ctx, deleteAccount, dollar_1)
	return err
}

const getAccountByProvider = `-- name: GetAccountByProvider :one
SELECT id, user_id, type, provider, provider_account_id, refresh_token, access_token, expires_at, token_type, scope, id_token, session_state
FROM authenserver_service.accounts
WHERE provider = $1 AND provider_account_id = $2
LIMIT 1
`

type GetAccountByProviderRow struct {
	ID                string      `json:"id"`
	UserID            string      `json:"user_id"`
	Type              string      `json:"type"`
	Provider          string      `json:"provider"`
	ProviderAccountID string      `json:"provider_account_id"`
	RefreshToken      pgtype.Text `json:"refresh_token"`
	AccessToken       pgtype.Text `json:"access_token"`
	ExpiresAt         pgtype.Int8 `json:"expires_at"`
	TokenType         pgtype.Text `json:"token_type"`
	Scope             pgtype.Text `json:"scope"`
	IDToken           pgtype.Text `json:"id_token"`
	SessionState      pgtype.Text `json:"session_state"`
}

func (q *Queries) GetAccountByProvider(ctx context.Context, column1 pgtype.Text, column2 pgtype.Text) (GetAccountByProviderRow, error) {
	row := q.db.QueryRow(ctx, getAccountByProvider, column1, column2)
	var i GetAccountByProviderRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Provider,
		&i.ProviderAccountID,
		&i.RefreshToken,
		&i.AccessToken,
		&i.ExpiresAt,
		&i.TokenType,
		&i.Scope,
		&i.IDToken,
		&i.SessionState,
	)
	return i, err
}

const getUserAccounts = `-- name: GetUserAccounts :many
SELECT id, user_id, type, provider, provider_account_id, refresh_token, access_token, expires_at, token_type, scope, id_token, session_state
FROM authenserver_service.accounts
WHERE user_id = $1
`

type GetUserAccountsRow struct {
	ID                string      `json:"id"`
	UserID            string      `json:"user_id"`
	Type              string      `json:"type"`
	Provider          string      `json:"provider"`
	ProviderAccountID string      `json:"provider_account_id"`
	RefreshToken      pgtype.Text `json:"refresh_token"`
	AccessToken       pgtype.Text `json:"access_token"`
	ExpiresAt         pgtype.Int8 `json:"expires_at"`
	TokenType         pgtype.Text `json:"token_type"`
	Scope             pgtype.Text `json:"scope"`
	IDToken           pgtype.Text `json:"id_token"`
	SessionState      pgtype.Text `json:"session_state"`
}

func (q *Queries) GetUserAccounts(ctx context.Context, dollar_1 pgtype.Text) ([]GetUserAccountsRow, error) {
	rows, err := q.db.Query(ctx, getUserAccounts, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserAccountsRow{}
	for rows.Next() {
		var i GetUserAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Provider,
			&i.ProviderAccountID,
			&i.RefreshToken,
			&i.AccessToken,
			&i.ExpiresAt,
			&i.TokenType,
			&i.Scope,
			&i.IDToken,
			&i.SessionState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountTokens = `-- name: UpdateAccountTokens :exec
UPDATE authenserver_service.accounts
SET
    refresh_token = $2,
    access_token = $3,
    expires_at = $4
WHERE id = $1
`

func (q *Queries) UpdateAccountTokens(ctx context.Context, column1 pgtype.Text, column2 pgtype.Text, column3 pgtype.Text, column4 pgtype.Int8) error {
	_, err := q.db.Exec(ctx, updateAccountTokens,
		column1,
		column2,
		column3,
		column4,
	)
	return err
}
