// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_logs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthLog = `-- name: CreateAuthLog :one
INSERT INTO authenserver_service.auth_logs (
    id, "userId", action, "ipAddress", "userAgent", timestamp
) VALUES (
    $1, $2, $3, $4, $5, NOW()
)
RETURNING id, "userId", action, "ipAddress", "userAgent", timestamp
`

type CreateAuthLogRow struct {
	ID        string      `json:"id"`
	UserId    pgtype.Text `json:"userId"`
	Action    string      `json:"action"`
	IpAddress pgtype.Text `json:"ipAddress"`
	UserAgent pgtype.Text `json:"userAgent"`
	Timestamp interface{} `json:"timestamp"`
}

func (q *Queries) CreateAuthLog(ctx context.Context, column1 pgtype.Text, column2 pgtype.Text, column3 pgtype.Text, column4 pgtype.Text, column5 pgtype.Text) (CreateAuthLogRow, error) {
	row := q.db.QueryRow(ctx, createAuthLog,
		column1,
		column2,
		column3,
		column4,
		column5,
	)
	var i CreateAuthLogRow
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Action,
		&i.IpAddress,
		&i.UserAgent,
		&i.Timestamp,
	)
	return i, err
}

const getAuthLogsByUser = `-- name: GetAuthLogsByUser :many
SELECT id, "userId", action, "ipAddress", "userAgent", timestamp
FROM authenserver_service.auth_logs
WHERE "userId" = $1
ORDER BY timestamp DESC
LIMIT $2 OFFSET $3
`

type GetAuthLogsByUserRow struct {
	ID        string      `json:"id"`
	UserId    pgtype.Text `json:"userId"`
	Action    string      `json:"action"`
	IpAddress pgtype.Text `json:"ipAddress"`
	UserAgent pgtype.Text `json:"userAgent"`
	Timestamp interface{} `json:"timestamp"`
}

func (q *Queries) GetAuthLogsByUser(ctx context.Context, column1 pgtype.Text, column2 pgtype.Int8, column3 pgtype.Int8) ([]GetAuthLogsByUserRow, error) {
	rows, err := q.db.Query(ctx, getAuthLogsByUser, column1, column2, column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAuthLogsByUserRow{}
	for rows.Next() {
		var i GetAuthLogsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.Action,
			&i.IpAddress,
			&i.UserAgent,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentAuthLogs = `-- name: GetRecentAuthLogs :many
SELECT id, "userId", action, "ipAddress", "userAgent", timestamp
FROM authenserver_service.auth_logs
ORDER BY timestamp DESC
LIMIT $1 OFFSET $2
`

type GetRecentAuthLogsRow struct {
	ID        string      `json:"id"`
	UserId    pgtype.Text `json:"userId"`
	Action    string      `json:"action"`
	IpAddress pgtype.Text `json:"ipAddress"`
	UserAgent pgtype.Text `json:"userAgent"`
	Timestamp interface{} `json:"timestamp"`
}

func (q *Queries) GetRecentAuthLogs(ctx context.Context, column1 pgtype.Int8, column2 pgtype.Int8) ([]GetRecentAuthLogsRow, error) {
	rows, err := q.db.Query(ctx, getRecentAuthLogs, column1, column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentAuthLogsRow{}
	for rows.Next() {
		var i GetRecentAuthLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.Action,
			&i.IpAddress,
			&i.UserAgent,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
