// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                string           `json:"id"`
	UserID            string           `json:"user_id"`
	Type              string           `json:"type"`
	Provider          string           `json:"provider"`
	ProviderAccountID string           `json:"provider_account_id"`
	RefreshToken      pgtype.Text      `json:"refresh_token"`
	AccessToken       pgtype.Text      `json:"access_token"`
	ExpiresAt         pgtype.Int8      `json:"expires_at"`
	TokenType         pgtype.Text      `json:"token_type"`
	Scope             pgtype.Text      `json:"scope"`
	IDToken           pgtype.Text      `json:"id_token"`
	SessionState      pgtype.Text      `json:"session_state"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
}

type AuthLog struct {
	ID        string           `json:"id"`
	UserID    pgtype.Text      `json:"user_id"`
	Action    string           `json:"action"`
	IpAddress pgtype.Text      `json:"ip_address"`
	UserAgent pgtype.Text      `json:"user_agent"`
	Timestamp pgtype.Timestamp `json:"timestamp"`
	Metadata  []byte           `json:"metadata"`
}

type Permission struct {
	ID          int32            `json:"id"`
	Slug        string           `json:"slug"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Role struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type RolePermission struct {
	RoleID       int32 `json:"role_id"`
	PermissionID int32 `json:"permission_id"`
}

type Session struct {
	ID           string           `json:"id"`
	SessionToken string           `json:"session_token"`
	UserID       string           `json:"user_id"`
	Expires      pgtype.Timestamp `json:"expires"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID            string           `json:"id"`
	Name          pgtype.Text      `json:"name"`
	Email         pgtype.Text      `json:"email"`
	EmailVerified pgtype.Timestamp `json:"email_verified"`
	Image         pgtype.Text      `json:"image"`
	Password      pgtype.Text      `json:"password"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type UserRole struct {
	UserID     string           `json:"user_id"`
	RoleID     int32            `json:"role_id"`
	AssignedAt pgtype.Timestamp `json:"assigned_at"`
}

type VerificationToken struct {
	Identifier string           `json:"identifier"`
	Token      string           `json:"token"`
	Expires    pgtype.Timestamp `json:"expires"`
}
