// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AssignRoleToUser(ctx context.Context, column1 pgtype.Text, column2 pgtype.Int4) error
	CountUsers(ctx context.Context) (pgtype.Int8, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error)
	CreateAuthLog(ctx context.Context, column1 pgtype.Text, column2 pgtype.Text, column3 pgtype.Text, column4 pgtype.Text, column5 pgtype.Text) (CreateAuthLogRow, error)
	CreateRole(ctx context.Context, column1 pgtype.Text, column2 pgtype.Text) (CreateRoleRow, error)
	CreateSession(ctx context.Context, column1 pgtype.Text, column2 pgtype.Text, column3 pgtype.Text, column4 pgtype.Timestamp) (CreateSessionRow, error)
	CreateUser(ctx context.Context, column1 pgtype.Text, column2 pgtype.Text, column3 pgtype.Text, column4 pgtype.Timestamp, column5 pgtype.Text, column6 pgtype.Text) (CreateUserRow, error)
	DeleteAccount(ctx context.Context, dollar_1 pgtype.Text) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteSession(ctx context.Context, dollar_1 pgtype.Text) error
	DeleteUser(ctx context.Context, dollar_1 pgtype.Text) error
	DeleteUserSessions(ctx context.Context, dollar_1 pgtype.Text) error
	GetAccountByProvider(ctx context.Context, column1 pgtype.Text, column2 pgtype.Text) (GetAccountByProviderRow, error)
	GetAuthLogsByUser(ctx context.Context, column1 pgtype.Text, column2 pgtype.Int8, column3 pgtype.Int8) ([]GetAuthLogsByUserRow, error)
	GetRecentAuthLogs(ctx context.Context, column1 pgtype.Int8, column2 pgtype.Int8) ([]GetRecentAuthLogsRow, error)
	GetRoleByID(ctx context.Context, dollar_1 pgtype.Int4) (GetRoleByIDRow, error)
	GetRoleByName(ctx context.Context, dollar_1 pgtype.Text) (GetRoleByNameRow, error)
	GetRolePermissions(ctx context.Context, dollar_1 pgtype.Int4) ([]GetRolePermissionsRow, error)
	GetSessionByToken(ctx context.Context, dollar_1 pgtype.Text) (GetSessionByTokenRow, error)
	GetUserAccounts(ctx context.Context, dollar_1 pgtype.Text) ([]GetUserAccountsRow, error)
	GetUserByEmail(ctx context.Context, dollar_1 pgtype.Text) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, dollar_1 pgtype.Text) (GetUserByIDRow, error)
	GetUserPermissions(ctx context.Context, dollar_1 pgtype.Text) ([]GetUserPermissionsRow, error)
	GetUserRoles(ctx context.Context, dollar_1 pgtype.Text) ([]GetUserRolesRow, error)
	ListRoles(ctx context.Context) ([]ListRolesRow, error)
	ListUsers(ctx context.Context, column1 pgtype.Int8, column2 pgtype.Int8) ([]ListUsersRow, error)
	RemoveRoleFromUser(ctx context.Context, column1 pgtype.Text, column2 pgtype.Int4) error
	UpdateAccountTokens(ctx context.Context, column1 pgtype.Text, column2 pgtype.Text, column3 pgtype.Text, column4 pgtype.Int8) error
	UpdateUser(ctx context.Context, column1 pgtype.Text, column2 pgtype.Text, column3 pgtype.Text, column4 pgtype.Timestamp, column5 pgtype.Text) (UpdateUserRow, error)
	UpdateUserPassword(ctx context.Context, column1 pgtype.Text, column2 pgtype.Text) error
}

var _ Querier = (*Queries)(nil)
