// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignRoleToUser = `-- name: AssignRoleToUser :exec
INSERT INTO authenserver_service.user_roles ("userId", "roleId")
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

func (q *Queries) AssignRoleToUser(ctx context.Context, column1 pgtype.Text, column2 pgtype.Int4) error {
	_, err := q.db.Exec(ctx, assignRoleToUser, column1, column2)
	return err
}

const createRole = `-- name: CreateRole :one
INSERT INTO authenserver_service.roles (name, description)
VALUES ($1, $2)
RETURNING id, name, description, created_at, updated_at
`

type CreateRoleRow struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateRole(ctx context.Context, column1 pgtype.Text, column2 pgtype.Text) (CreateRoleRow, error) {
	row := q.db.QueryRow(ctx, createRole, column1, column2)
	var i CreateRoleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, name, description, created_at, updated_at
FROM authenserver_service.roles
WHERE id = $1 LIMIT 1
`

type GetRoleByIDRow struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetRoleByID(ctx context.Context, dollar_1 pgtype.Int4) (GetRoleByIDRow, error) {
	row := q.db.QueryRow(ctx, getRoleByID, dollar_1)
	var i GetRoleByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, description, created_at, updated_at
FROM authenserver_service.roles
WHERE name = $1 LIMIT 1
`

type GetRoleByNameRow struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetRoleByName(ctx context.Context, dollar_1 pgtype.Text) (GetRoleByNameRow, error) {
	row := q.db.QueryRow(ctx, getRoleByName, dollar_1)
	var i GetRoleByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRolePermissions = `-- name: GetRolePermissions :many
SELECT p.id, p.slug, p.description, p.created_at
FROM authenserver_service.permissions p
INNER JOIN authenserver_service.role_permissions rp ON p.id = rp."permissionId"
WHERE rp."roleId" = $1
`

type GetRolePermissionsRow struct {
	ID          int32            `json:"id"`
	Slug        string           `json:"slug"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetRolePermissions(ctx context.Context, dollar_1 pgtype.Int4) ([]GetRolePermissionsRow, error) {
	rows, err := q.db.Query(ctx, getRolePermissions, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRolePermissionsRow{}
	for rows.Next() {
		var i GetRolePermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPermissions = `-- name: GetUserPermissions :many
SELECT DISTINCT p.id, p.slug, p.description, p.created_at
FROM authenserver_service.permissions p
INNER JOIN authenserver_service.role_permissions rp ON p.id = rp."permissionId"
INNER JOIN authenserver_service.user_roles ur ON rp."roleId" = ur."roleId"
WHERE ur."userId" = $1
`

type GetUserPermissionsRow struct {
	ID          int32            `json:"id"`
	Slug        string           `json:"slug"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetUserPermissions(ctx context.Context, dollar_1 pgtype.Text) ([]GetUserPermissionsRow, error) {
	rows, err := q.db.Query(ctx, getUserPermissions, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserPermissionsRow{}
	for rows.Next() {
		var i GetUserPermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT r.id, r.name, r.description, r.created_at, r.updated_at
FROM authenserver_service.roles r
INNER JOIN authenserver_service.user_roles ur ON r.id = ur."roleId"
WHERE ur."userId" = $1
`

type GetUserRolesRow struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetUserRoles(ctx context.Context, dollar_1 pgtype.Text) ([]GetUserRolesRow, error) {
	rows, err := q.db.Query(ctx, getUserRoles, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserRolesRow{}
	for rows.Next() {
		var i GetUserRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, description, created_at, updated_at
FROM authenserver_service.roles
ORDER BY name
`

type ListRolesRow struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListRoles(ctx context.Context) ([]ListRolesRow, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolesRow{}
	for rows.Next() {
		var i ListRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoleFromUser = `-- name: RemoveRoleFromUser :exec
DELETE FROM authenserver_service.user_roles
WHERE "userId" = $1 AND "roleId" = $2
`

func (q *Queries) RemoveRoleFromUser(ctx context.Context, column1 pgtype.Text, column2 pgtype.Int4) error {
	_, err := q.db.Exec(ctx, removeRoleFromUser, column1, column2)
	return err
}
