// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO authenserver_service.sessions (
    id, "sessionToken", "userId", expires
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, "sessionToken", "userId", expires
`

type CreateSessionRow struct {
	ID           string      `json:"id"`
	SessionToken string      `json:"sessionToken"`
	UserId       string      `json:"userId"`
	Expires      interface{} `json:"expires"`
}

func (q *Queries) CreateSession(ctx context.Context, column1 pgtype.Text, column2 pgtype.Text, column3 pgtype.Text, column4 pgtype.Timestamp) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession,
		column1,
		column2,
		column3,
		column4,
	)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.SessionToken,
		&i.UserId,
		&i.Expires,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM authenserver_service.sessions
WHERE expires < NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM authenserver_service.sessions
WHERE "sessionToken" = $1
`

func (q *Queries) DeleteSession(ctx context.Context, dollar_1 pgtype.Text) error {
	_, err := q.db.Exec(ctx, deleteSession, dollar_1)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM authenserver_service.sessions
WHERE "userId" = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, dollar_1 pgtype.Text) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, dollar_1)
	return err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, "sessionToken", "userId", expires
FROM authenserver_service.sessions
WHERE "sessionToken" = $1 AND expires > NOW()
LIMIT 1
`

type GetSessionByTokenRow struct {
	ID           string      `json:"id"`
	SessionToken string      `json:"sessionToken"`
	UserId       string      `json:"userId"`
	Expires      interface{} `json:"expires"`
}

func (q *Queries) GetSessionByToken(ctx context.Context, dollar_1 pgtype.Text) (GetSessionByTokenRow, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, dollar_1)
	var i GetSessionByTokenRow
	err := row.Scan(
		&i.ID,
		&i.SessionToken,
		&i.UserId,
		&i.Expires,
	)
	return i, err
}
