// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM authenserver_service.users
`

func (q *Queries) CountUsers(ctx context.Context) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count pgtype.Int8
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO authenserver_service.users (
    id, name, email, "emailVerified", image, password, "createdAt", "updatedAt"
) VALUES (
    $1, $2, $3, $4, $5, $6, NOW(), NOW()
)
RETURNING id, name, email, "emailVerified", image, password, "createdAt", "updatedAt"
`

type CreateUserRow struct {
	ID            string      `json:"id"`
	Name          pgtype.Text `json:"name"`
	Email         pgtype.Text `json:"email"`
	EmailVerified interface{} `json:"emailVerified"`
	Image         pgtype.Text `json:"image"`
	Password      pgtype.Text `json:"password"`
	CreatedAt     interface{} `json:"createdAt"`
	UpdatedAt     interface{} `json:"updatedAt"`
}

func (q *Queries) CreateUser(ctx context.Context, column1 pgtype.Text, column2 pgtype.Text, column3 pgtype.Text, column4 pgtype.Timestamp, column5 pgtype.Text, column6 pgtype.Text) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		column1,
		column2,
		column3,
		column4,
		column5,
		column6,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM authenserver_service.users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, dollar_1 pgtype.Text) error {
	_, err := q.db.Exec(ctx, deleteUser, dollar_1)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, "emailVerified", image, password, "createdAt", "updatedAt"
FROM authenserver_service.users
WHERE email = $1 LIMIT 1
`

type GetUserByEmailRow struct {
	ID            string      `json:"id"`
	Name          pgtype.Text `json:"name"`
	Email         pgtype.Text `json:"email"`
	EmailVerified interface{} `json:"emailVerified"`
	Image         pgtype.Text `json:"image"`
	Password      pgtype.Text `json:"password"`
	CreatedAt     interface{} `json:"createdAt"`
	UpdatedAt     interface{} `json:"updatedAt"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, dollar_1 pgtype.Text) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, dollar_1)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, "emailVerified", image, password, "createdAt", "updatedAt"
FROM authenserver_service.users
WHERE id = $1 LIMIT 1
`

type GetUserByIDRow struct {
	ID            string      `json:"id"`
	Name          pgtype.Text `json:"name"`
	Email         pgtype.Text `json:"email"`
	EmailVerified interface{} `json:"emailVerified"`
	Image         pgtype.Text `json:"image"`
	Password      pgtype.Text `json:"password"`
	CreatedAt     interface{} `json:"createdAt"`
	UpdatedAt     interface{} `json:"updatedAt"`
}

func (q *Queries) GetUserByID(ctx context.Context, dollar_1 pgtype.Text) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, dollar_1)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, "emailVerified", image, password, "createdAt", "updatedAt"
FROM authenserver_service.users
ORDER BY "createdAt" DESC
LIMIT $1 OFFSET $2
`

type ListUsersRow struct {
	ID            string      `json:"id"`
	Name          pgtype.Text `json:"name"`
	Email         pgtype.Text `json:"email"`
	EmailVerified interface{} `json:"emailVerified"`
	Image         pgtype.Text `json:"image"`
	Password      pgtype.Text `json:"password"`
	CreatedAt     interface{} `json:"createdAt"`
	UpdatedAt     interface{} `json:"updatedAt"`
}

func (q *Queries) ListUsers(ctx context.Context, column1 pgtype.Int8, column2 pgtype.Int8) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, column1, column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.EmailVerified,
			&i.Image,
			&i.Password,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE authenserver_service.users
SET
    name = COALESCE($2, name),
    email = COALESCE($3, email),
    "emailVerified" = COALESCE($4, "emailVerified"),
    image = COALESCE($5, image),
    "updatedAt" = NOW()
WHERE id = $1
RETURNING id, name, email, "emailVerified", image, password, "createdAt", "updatedAt"
`

type UpdateUserRow struct {
	ID            string      `json:"id"`
	Name          pgtype.Text `json:"name"`
	Email         pgtype.Text `json:"email"`
	EmailVerified interface{} `json:"emailVerified"`
	Image         pgtype.Text `json:"image"`
	Password      pgtype.Text `json:"password"`
	CreatedAt     interface{} `json:"createdAt"`
	UpdatedAt     interface{} `json:"updatedAt"`
}

func (q *Queries) UpdateUser(ctx context.Context, column1 pgtype.Text, column2 pgtype.Text, column3 pgtype.Text, column4 pgtype.Timestamp, column5 pgtype.Text) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		column1,
		column2,
		column3,
		column4,
		column5,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE authenserver_service.users
SET password = $2, "updatedAt" = NOW()
WHERE id = $1
`

func (q *Queries) UpdateUserPassword(ctx context.Context, column1 pgtype.Text, column2 pgtype.Text) error {
	_, err := q.db.Exec(ctx, updateUserPassword, column1, column2)
	return err
}
